remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme 

title: danielpickett.dev
accent_color: '#2d72d9'

description: >
    Hello! I'm <a href="https://danielpickett.dev/about">Daniel</a>, an undergraduate computer science student in Boston, MA.
    Here are some things I've worked on so far. <span style="font-style: normal;">😄</span>
    
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Posts
    url: /posts

# Google Analytics
google_analytics: UA-102932229-3

footer:
    content: "&copy; 2021 Daniel Pickett"
    has_social: true

plugins:
  - jekyll-paginate
  - jekyll-target-blank

paginate: 3
paginate_path: '/page:num/'

permalink: /:title
