remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme

lang: en-US

baseurl: ""
url: "https://danielpickett.dev"

title: danielpickett.dev
accent_color: "#2d72d9"

description: >
  <span style="font-style: normal;"> Hello! I'm Daniel, a Software Engineer in Boston, MA. 🙂</span>

navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Tech
    url: /tech
  - text: Cooking
    url: /cooking

# Google Analytics
google_analytics: UA-102932229-3

footer:
  content: "&copy; 2025 Daniel Pickett"
  has_social: true

plugins:
  - jekyll-paginate
  - jekyll-target-blank

paginate: 3
paginate_path: "/page:num/"

permalink: /:title

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

collections:
  tech:
    output: true
    permalink: /:collection/:title
