remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme 

title: danielpickett.dev
accent_color: '#2d72d9'

description: >
    Hello! I'm Daniel, an undergraduate computer science student in Boston, MA.
    Here are some things I've worked on so far. <span style="font-style: normal;">😄</span>

footer:
    content: "&copy; 2021 Daniel Pickett"
    has_social: true
