remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme

lang: en-US

baseurl: ""
url: "https://danielpickett.dev"

title: danielpickett.dev
accent_color: '#2d72d9'

description: >
    <span style="font-style: normal;"> Hello! I'm <a href="https://danielpickett.dev/about">Daniel</a>, a Software Engineer in Boston at <a href="https://pos.toasttab.com">Toast</a> 🍞</span>

navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Posts
    url: /posts

# Google Analytics
google_analytics: UA-102932229-3

footer:
    content: "&copy; 2023 Daniel Pickett"
    has_social: true

plugins:
  - jekyll-paginate
  - jekyll-target-blank

paginate: 3
paginate_path: '/page:num/'

permalink: /:title

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed
